/**
 * Created by HHH on 2017/10/25.
 */
export const SET_SINGER = 'SET_SINGER'
export const SET_PLAYER_CREATED = 'SET_PLAYER_CREATED'
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE'
export const SET_PLAYER_FULLPAGE = 'SET_PLAYER_FULLPAGE'
export const SET_PLAYER_PLAYLIST = 'SET_PLAYER_PLAYLIST'
export const SET_PLAYE_SEQUENCELIST = 'SET_PLAYE_SEQUENCELIST'
export const SET_PLAYER_PLAYMODE = 'SET_PLAYER_PLAYMODE'
export const SET_PLAYER_CURRENT = 'SET_PLAYER_CURRENT'
